# Exercício:

## 01 – Obtenha os resultados e retorne o código Python dos seguintes cálculos:

<br>a = 2.0 + 3.0 / 5.0 == 10
<br>b = (a + 10.2) - 5.0 * 2.0 <= 2.9
<br>c = 10 <= a / b + 33.8 < 100
<br>d = 5 != a / (b + c)
<br>e = 33 == d * 2

In [25]:
import pandas as pd
import numpy as np

a = 2.0 + (3.0/5.0)
print(a==10)
b = (a + 10.2) - (5.0 * 2.0)
print(b<=2.9)
c = (a/b + 33.8)
print(10<=c<100)
d = a/(b+c)
print(5 != d)
e = d*2
print(33==e)

False
True
True
True
False


## 02 – Altere os operadores relacionais para modificar o resultado de cada uma das comparações.

<br>('a',1,True,'b',0,False) != ('a',True,1,'b',False,0)
<br>['a',1,True,'b',0,False] != ('a',True,1,'b',False,0)
<br>['a',1,True,'b',0,False] != ['a',True,1,'b',False,0]
<br>['a',1,True,'b',0,False] > ['a',True,1]
<br>['a',1,True,'b',0,False] == 1
<br>['a',True,1] <= ['a',True,1] < ['a',1,True,'b',0,False]

In [26]:
print(('a',1,True,'b',0,False) == ('a',True,1,'b',False,0),"\n",
['a',1,True,'b',0,False] != ('a',True,1,'b',False,0),"\n",
['a',1,True,'b',0,False] == ['a',True,1,'b',False,0],"\n",
['a',1,True,'b',0,False] > ['a',True,1],"\n",
['a',1,True,'b',0,False] != 1,"\n",
['a',True,1] <= ['a',True,1] < ['a',1,True,'b',0,False])

True 
 True 
 True 
 True 
 True 
 True


## 03 – Usando o método DataFrame.to_csv(‘nome_do_arquivo.csv’) exporte o objeto obtido no exercício 10 da aula anterior para um arquivo CSV. Usando o método pd.read_csv(‘nome_do_arquivo.csv’) instancie uma DataFrame. Use o valor ‘Unnamed: 0’ no parâmetro index_col, para ajustar o index. Arredonde os valores para até três casas decimais, usando o método round().
Recupere a DataFrame.

In [27]:
Ultima_coluna = pd.read_csv('ultima_Coluna.csv', index_col='Unnamed: 0')
Ultima_linha = pd.read_csv('ultima_linha.csv', index_col='Unnamed: 0')
Ultima_coluna = Ultima_coluna.round(3)
Ultima_linha = Ultima_linha.round(3)
print(Ultima_coluna,"\n\n",Ultima_linha)


                                 0      1      2      3     4      5
count                         1.00  1.000  1.000  1.000  1.00  1.000
media_das_medias_das_linhas  10.05  2.329  1.509  9.137  2.05  5.015
std                            NaN    NaN    NaN    NaN   NaN    NaN
min                          10.05  2.329  1.509  9.137  2.05  5.015
25%                          10.05  2.329  1.509  9.137  2.05  5.015
50%                          10.05  2.329  1.509  9.137  2.05  5.015
75%                          10.05  2.329  1.509  9.137  2.05  5.015
max                          10.05  2.329  1.509  9.137  2.05  5.015 

                              0      1      2      3  media_linhas
count                    1.000  1.000  1.000  1.000         1.000
media_das_medias_coluna  7.881  2.149  7.881  2.149         5.015
std                        NaN    NaN    NaN    NaN           NaN
min                      7.881  2.149  7.881  2.149         5.015
25%                      7.881  2.149  7.881  

## 04 – Instancie um numpy array que apresente o mesmo formato (linhas e colunas) da DataFrame. Este array deve conter apenas inteiros uns.
Recupere o array.

Obs.: Procure na internet o método numpy.ones()

In [28]:
tam_linha = Ultima_linha.shape
tam_coluna = Ultima_coluna.shape
array_linha_uns = np.ones(tam_linha, dtype=int)
array_coluna_uns = np.ones(tam_coluna, dtype=int)
print(" tamanho colunas\n",array_coluna_uns,"\n\n","tamaho linhas \n",array_linha_uns)

 tamanho colunas
 [[1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]] 

 tamaho linhas 
 [[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


## 05 – Quantos dos valores contidos na DataFrame são iguais aos valores no array?

In [29]:
comp_linha = array_linha_uns == Ultima_linha.values
comp_linha.sum()
comp_coluna = array_coluna_uns == Ultima_coluna.values
comp_coluna.sum()
print(" array linhas \n",comp_linha.sum(),"\n\n","array colunas\n",comp_coluna.sum())

 array linhas 
 5 

 array colunas
 6


## 06 – Quantos dos valores contidos na DataFrame são superiores aos valores no array?

In [30]:
comp_linha = array_linha_uns < Ultima_linha.values
comp_linha.sum()
comp_coluna = array_coluna_uns < Ultima_coluna.values
comp_coluna.sum()
print(" array linhas \n",comp_linha.sum(),"\n\n","array colunas \n",comp_coluna.sum())

 array linhas 
 30 

 array colunas 
 36


## 07 – Quantos dos valores contidos na DataFrame são iguais ou inferiores aos valores no array?

In [31]:
comp_linha = array_linha_uns >= Ultima_linha.values
comp_linha.sum()
comp_coluna = array_coluna_uns >= Ultima_coluna.values
comp_coluna.sum()
print(" array linhas \n",comp_linha.sum(),"\n\n","array colunas \n",comp_coluna.sum())

 array linhas 
 5 

 array colunas 
 6


## 08 – Quantos dos valores contidos na DataFrame estão entre 0 e 1?

In [32]:
comp_linha = (0 < Ultima_linha.values) & (Ultima_linha.values < 1)
comp_linha.sum()
comp_coluna = (0 < Ultima_coluna.values) & (Ultima_coluna.values < 1)
comp_coluna.sum()
print(" array linhas \n",comp_linha.sum(),"\n\n","array colunas \n",comp_coluna.sum())

 array linhas 
 0 

 array colunas 
 0


## 09 – Quantos dos valores das médias das linhas são inferiores ou iguais à 5?

Obs 1.: Usando o método de classe, você pode converter qualquer objeto em outra classe. Ex. obj = list(array)

Obs 2.: Assim com o objeto da classe str, listas também possuem a função count()

In [33]:
numero = Ultima_coluna.loc["media_das_medias_das_linhas"].values <= 5
numero = sum(numero)
print("o numero de valores da media das linhas que são inferiores ou iguas a 5 é de =",numero)

o numero de valores da media das linhas que são inferiores ou iguas a 5 é de = 3


## 10 – Quantos dos valores das médias das colunas são superiores à 5?

In [34]:
numero = Ultima_linha.loc["media_das_medias_coluna"].values > 5
numero = sum(numero)
print("o numero de valores da media das colunas que são superiores 5 é de =",numero)

o numero de valores da media das colunas que são superiores 5 é de = 3
