# Explicação Rotina

https://1drv.ms/v/c/808ebfd9a0d86213/IQA1p5nBtUMiS4C1k70ZRFf3ASpmGVhaRHc_ibt9GJbkfww?e=9Er6z5

# Exercício:

## 01 – Cite três vantagens do uso das funções e duas características que toda função deva ter?

R.: vanagens - melhor organização e leitura do codigo, Otimização do codigo, facilitar a manutenção ou alteração do codigo.
Toda a função deve ter um nome para ser chamada e deve ter um retorno unitario.

## Responda a pergunta do exercício 2 da aula 10, usando funções:<br>
Instancie um objeto da classe NumPy array, contendo 5 valores quantitativos randômicos normalmente distribuídos, com média 10 e desvio padrão 3.<br><br>
Quantos e quais são os valores superiores a 10?

In [37]:
import numpy as np
import pandas as pd

def valor_maior_que (array_valor: np.ndarray, i: int) -> list:
    array_rand_filtro = []
    for valor in array_valor:
        if valor > i:
            array_rand_filtro.append(float(valor))
    return array_rand_filtro

def qnt_maior_que (array_valor: np.ndarray, i: int) -> int:
    a = 0
    for valor in array_valor:
        if valor > i:
            a += 1
    return a

array_rand = np.random.normal(10,3,5)
lisa_maior_que = valor_maior_que(array_rand, 10)
numero_maior_que = qnt_maior_que(array_rand, 10)


print("maiores que - ",lisa_maior_que, "\n","numero de valores superiores a - ", numero_maior_que)
array_rand

maiores que -  [10.602948814086457, 10.830674036628356, 13.235547991709794, 15.545308405134755] 
 numero de valores superiores a -  4


array([ 1.91547008, 10.60294881, 10.83067404, 13.23554799, 15.54530841])

## 02 – Descreva o racional da sua resposta:

R.: primeiramente foi defindias duas funções. Uma função recebe um array e um int e usa um for e um if para comparar se cada objeto do array é maior que o int fornecido, caso seja esse int é concatenado a uma lista, e no final a função retorna a lista. 
A outra função recebe tambem um array e um int e de forma semelhante ele compara cada objeto do array com o int, caso o objeto seja maior que o int fornecido ele suma 1 a uma variavel contadora que inicialmente é declarada como 0. no final a função retorna a variavel contadora.
Então, um array aleatório de 5 valores normalmente distribuidos com média 10 e desvio padrão 3 é declarado e usado como argumento nas funçoes, juntamento do numro que queromos comparar, que no caso é 10

## 03 – Desenhe o fluxograma da resposta:

<img src="img/Aula 12 exer 3.png" width="800"/>

## 04 – Escreva o programa em Python:

In [4]:
import numpy as np
import pandas as pd

def valor_maior_que (array_valor: np.ndarray, i: int) -> list:
    array_rand_filtro = []
    for valor in array_valor:
        if valor > i:
            array_rand_filtro.append(float(valor))
    return array_rand_filtro

def qnt_maior_que (array_valor: np.ndarray, i: int) -> int:
    a = 0
    for valor in array_valor:
        if valor > i:
            a += 1
    return a

array_rand = np.random.normal(10,3,5)
lisa_maior_que = valor_maior_que(array_rand, 10)
numero_maior_que = qnt_maior_que(array_rand, 10)


print("maiores que - ",lisa_maior_que, "\n","numero de valores superiores a - ", numero_maior_que)
array_rand

maiores que -  [12.25056833505553] 
 numero de valores superiores a -  1


array([12.25056834,  9.9946995 ,  9.65844054,  9.79859468,  9.9308852 ])

## 05 – Seria possível, com o racional proposto, saber quantos e quais valores são superiores a 20? Porque?

Sim, seria. uma vez que podemos somente alterar um argumento recebido pela função definda para alterar qual o valor que sera comparado na função 

In [21]:
import numpy as np
import pandas as pd

def valor_maior_que (array_valor: np.ndarray, i: int) -> list:
    array_rand_filtro = []
    for valor in array_valor:
        if valor > i:
            array_rand_filtro.append(float(valor))
    return array_rand_filtro

def qnt_maior_que (array_valor: np.ndarray, i: int) -> int:
    a = 0
    for valor in array_valor:
        if valor > i:
            a += 1
    return a

array_rand = np.random.normal(10,3,5)
lisa_maior_que = valor_maior_que(array_rand, 20)
numero_maior_que = qnt_maior_que(array_rand, 20)


print("maiores que - ",lisa_maior_que, "\n","numero de valores superiores a - ", numero_maior_que)
array_rand

maiores que -  [] 
 numero de valores superiores a -  0


array([12.71167603, 16.1870615 ,  3.74286974,  0.40835223,  9.04663477])

## Desenvolva um programa de computador que retorne a média de um conjunto de valores.

## 06 – Descreva o racional da sua resposta:

R.: o programa recebe uma lista de valores, ele então definie uma obejto "n" com o numero de objetos na lista, ele tambem define um objeto "s" com a soma dos valores de todos os objetos da lista, ele define um objeto "m" com a razão de "s" por "n", ele então retorna "m"

## 07 – Desenhe o fluxograma da resposta:

<img src="img/aula 12 exer 7.png" width="150"/>

## 07 – Escreva o programa em Python:

In [54]:
lista_numeros = np.random.randint(0, 10, size=5).tolist()
lista_numeros

def media (lista_numeros: list) -> float:
    n = len(lista_numeros)
    s = sum(lista_numeros)
    try:
        m = s/n
        return m
    except ZeroDivisionError:
        return "Erro: da para dividir por zero não"
    except ZeroDivisionError:
        return "Erro: os objetos compativeis para a divisão"
    
print(f"os valores são {lista_numeros}, a media é deles é {media(lista_numeros)}")

os valores são [7, 5, 8, 5, 1], a media é deles é 5.2


## 09 – Desenvolva um programa de computador que retorne a divisão de dois objetos simples. Seu programa deve ser capaz de reconhecer a classe destes objetos e o valor, antes de retornar ao usuário.

In [56]:
obj1 = 1
obj2 = 2

def diviao_obj_simpl (obj1: int, obj2: int) -> float:
    print(f"Objeto 1: Classe {type(obj1)} | Valor: {obj1}")
    print(f"Objeto 2: Classe {type(obj2)} | Valor: {obj2}")
    try:
        d = obj1/obj2
        return d
    except ZeroDivisionError:
        return "Erro: da para dividir por zero não"
    except ZeroDivisionError:
        return "Erro: os objetos compativeis para a divisão"

print(f"\nos objetos são {obj1} e {obj2}, a razão deles é {diviao_obj_simpl(obj1,obj2)}")




Objeto 1: Classe <class 'int'> | Valor: 1
Objeto 2: Classe <class 'int'> | Valor: 2

os objetos são 1 e 2, a razão deles é 0.5


## 10 – Desenvolva um programa de computador que retorne a divisão de dois objetos compostos. Seu programa deve ser capaz de reconhecer a classe destes objetos e o valor, antes de retornar ao usuário.

In [100]:
obj1 = np.random.randint(0, 10, size=5).tolist()
obj2 = np.random.randint(1, 10, size=5)

def diviao_obj_simpl (obj1: int, obj2: int) -> float:
    print(f"Objeto 1: Classe {type(obj1)} | Valor: {obj1}")
    print(f"Objeto 2: Classe {type(obj2)} | Valor: {obj2}")

    val_obj1 = obj1.values if hasattr(obj1, 'values') else obj1
    val_obj2 = obj2.values if hasattr(obj2, 'values') else obj2

    if 0 in val_obj2:
        return "Erro: Existe um zero no divisor."

    try:
        d = (val_obj1/val_obj2).tolist()
        return d
    except ZeroDivisionError:
        return "Erro: da para dividir por zero não"
    except ZeroDivisionError:
        return "Erro: os objetos compativeis para a divisão"

print(f"\nos objetos são {obj1} e {obj2.tolist()}, a razão deles é {diviao_obj_simpl(obj1,obj2)}")

Objeto 1: Classe <class 'list'> | Valor: [5, 0, 5, 3, 3]
Objeto 2: Classe <class 'numpy.ndarray'> | Valor: [2 7 1 5 5]

os objetos são [5, 0, 5, 3, 3] e [2, 7, 1, 5, 5], a razão deles é [2.5, 0.0, 5.0, 0.6, 0.6]
